
"use client";

import Image from 'next/image';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { AiWordProblemGameUI } from '@/components/math/ai-word-problem-game-ui';
import { Brain, MessageCircleQuestion } from 'lucide-react'; 

export default function AiWordProblemPage() {
  return (
    <div className="space-y-8">
      <div className="mb-6">
        <Button asChild variant="outline" className="group">
          <Link href="/math">
            <ArrowLeft className="mr-2 h-4 w-4 transition-transform group-hover:-translate-x-1" />
            Back to Math Zone
          </Link>
        </Button>
      </div>
      <header className="text-center space-y-4 animate-in fade-in-0 slide-in-from-top-10 duration-700 ease-out">
        <div className="relative w-full max-w-md mx-auto h-48 md:h-64 rounded-lg overflow-hidden shadow-md">
          <Image
            src="https://images.unsplash.com/photo-1722962496035-d6c08f9085be?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGNoaWxkcmVuJTIwbWF0aGVtYXRpY3N8ZW58MHx8MHx8fDA%3D" 
            alt="Children collaborating on a math word problem"
            layout="fill"
            objectFit="cover"
            className="rounded-lg"
            data-ai-hint="kids numbers" 
          />
           <div className="absolute inset-0 bg-black/60" /> {/* Dark overlay */}
           <div className="absolute inset-0 flex flex-col items-center justify-center p-2 text-center">
             <MessageCircleQuestion className="h-10 w-10 md:h-12 md:w-12 text-primary drop-shadow-lg" aria-hidden="true" />
             <h1 className="text-2xl md:text-3xl font-bold text-gradient-primary-accent mt-1 drop-shadow-md">AI Math Word Problems</h1>
             <p className="text-sm md:text-md text-gray-100 drop-shadow-sm">Solve engaging word problems generated by AI!</p>
           </div>
        </div>
      </header>
      
      <AiWordProblemGameUI />
    </div>
  );
}
