
"use client";

import Image from 'next/image';
import { AiWordProblemGameUI } from '@/components/math/ai-word-problem-game-ui';
import { Brain } from 'lucide-react';

export default function AiWordProblemPage() {
  return (
    <div className="space-y-8">
      <header className="text-center space-y-4 animate-in fade-in-0 slide-in-from-top-10 duration-700 ease-out">
        <div className="relative w-full max-w-xs mx-auto h-32 md:h-40 rounded-lg overflow-hidden shadow-md">
          <Image
            src="https://picsum.photos/300/200"
            alt="Child thinking about a math problem"
            layout="fill"
            objectFit="cover"
            className="rounded-lg"
            data-ai-hint="child thinking math"
          />
           <div className="absolute inset-0 bg-gradient-to-t from-background/70 to-transparent flex flex-col items-center justify-center p-2">
             <Brain className="h-10 w-10 md:h-12 md:w-12 text-primary drop-shadow-lg" aria-hidden="true" />
           </div>
        </div>
        <h1 className="text-3xl font-bold text-gradient-primary-accent">AI Math Word Problems</h1>
        <p className="text-md text-muted-foreground">Solve engaging word problems generated by AI!</p>
      </header>
      
      <AiWordProblemGameUI />
    </div>
  );
}
