
"use client";

import Link from 'next/link';
import Image from 'next/image';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Calculator, TableIcon as TimesTableIcon, Sigma, Puzzle, Scaling, ChevronsRight, Brain, BookOpen } from 'lucide-react';

export default function MathZonePage() {
  const mathSections = [
    {
      title: "AI Word Problems",
      description: "Solve math word problems generated by AI. Choose difficulty and operation.",
      href: "/math/ai-word-problem",
      icon: Brain,
      dataAiHint: "AI brain numbers",
    },
    {
      title: "AI Story Problems",
      description: "Read engaging stories and solve math problems related to them. AI-generated!",
      href: "/math/ai-story-problem",
      icon: BookOpen, // Consider a story/book icon
      dataAiHint: "AI story book math",
    },
    {
      title: "Arithmetic Games",
      description: "Sharpen your skills with fun and interactive arithmetic challenges.",
      href: "/math/arithmetic-game",
      icon: Puzzle,
      dataAiHint: "chalkboard numbers",
    },
    {
      title: "Times Table Practice",
      description: "Master your multiplication tables with targeted practice.",
      href: "/math/times-table",
      icon: TimesTableIcon,
      dataAiHint: "multiplication grid",
    },
    {
      title: "Number Comparison",
      description: "Compare numbers and choose the biggest or smallest.",
      href: "/math/number-comparison",
      icon: Scaling,
      dataAiHint: "numbers comparison chart",
    },
    {
      title: "Number Sequencing",
      description: "Find the missing number in a sequence or complete patterns.",
      href: "/math/number-sequencing",
      icon: ChevronsRight,
      dataAiHint: "number line sequence",
    },
  ];

  return (
    <div className="space-y-8">
      <header className="text-center space-y-4 animate-in fade-in-0 slide-in-from-top-10 duration-700 ease-out">
        <div className="relative w-full max-w-md mx-auto h-48 md:h-64 rounded-lg overflow-hidden shadow-lg">
          <Image 
            src="https://picsum.photos/600/400" 
            alt="Abstract math background"
            layout="fill"
            objectFit="cover"
            className="rounded-lg"
            data-ai-hint="abstract math education"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent flex flex-col items-center justify-center p-4">
            <Sigma className="h-16 w-16 text-primary drop-shadow-lg animate-in fade-in zoom-in-50 duration-1000 delay-200" aria-hidden="true" />
            <h1 className="text-4xl font-bold text-gradient-primary-accent mt-2">Math Zone</h1>
            <p className="text-lg text-foreground/90 drop-shadow-sm">Explore various math activities and games.</p>
          </div>
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {mathSections.map((section, index) => (
          <Card 
            key={section.title} 
            className="shadow-lg hover:shadow-xl transition-shadow duration-300 ease-in-out animate-in fade-in-0 slide-in-from-bottom-5 duration-500 ease-out"
            style={{ animationDelay: `${100 + index * 100}ms` }} // Staggered animation
          >
            <CardHeader className="flex flex-row items-center gap-4 space-y-0 pb-2">
              <section.icon className="h-10 w-10 text-accent" aria-hidden="true" />
              <div className="flex-1">
                <CardTitle className="text-2xl font-semibold text-primary">{section.title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <CardDescription className="text-base text-foreground/80 min-h-[40px]">
                {section.description}
              </CardDescription>
              <Button asChild className="w-full btn-glow">
                <Link href={section.href}>
                  Go to {section.title}
                </Link>
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

