
"use client";

import Link from 'next/link';
import Image from 'next/image';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Calculator, TableIcon as TimesTableIcon, Sigma, Puzzle, Scaling, ChevronsRight, Brain, BookOpen, Divide, Percent, MessageCircleQuestion, MessageSquarePlus, Footprints, Grid3x3 } from 'lucide-react'; 

export default function MathZonePage() {
  const mathSections = [
    {
      title: "AI Word Problems",
      description: "Solve math word problems generated by AI. Choose difficulty and operation.",
      href: "/math/ai-word-problem",
      icon: MessageCircleQuestion, 
      imageSrc: "https://images.unsplash.com/photo-1722962496035-d6c08f9085be?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGNoaWxkcmVuJTIwbWF0aGVtYXRpY3N8ZW58MHx8MHx8fDA%3D",
      dataAiHint: "kids numbers", 
    },
    {
      title: "AI Story Problems",
      description: "Read engaging stories and solve math problems related to them. AI-generated!",
      href: "/math/ai-story-problem",
      icon: MessageSquarePlus, 
      imageSrc: "https://images.unsplash.com/photo-1685358279653-868c0b99fe6c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNoaWxkcmVuJTIwbWF0aGVtYXRpY3N8ZW58MHx8MHx8fDA%3D",
      dataAiHint: "child math", 
    },
    {
      title: "Matteo - Math Tutor",
      description: "Ask Matteo any math question. Get help with concepts or problem-solving steps!",
      href: "/math/math-tutor",
      icon: Brain, // Using Brain icon for tutor
      imageSrc: "https://images.unsplash.com/photo-1596495577886-d925057463B0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fG1hdGglMjB0dXRvcnxlbnwwfHwwfHx8MA%3D%3D",
      dataAiHint: "AI math tutor",
    },
    {
      title: "Arithmetic Games",
      description: "Sharpen your skills with fun and interactive arithmetic challenges.",
      href: "/math/arithmetic-game",
      icon: Calculator, 
      imageSrc: "https://images.unsplash.com/photo-1634128221889-82ed6efebfc3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fGNoaWxkcmVuJTIwbWF0aGVtYXRpY3N8ZW58MHx8MHx8fDA%3D",
      dataAiHint: "math game", 
    },
    {
      title: "Times Table Practice",
      description: "Master your multiplication tables with targeted practice.",
      href: "/math/times-table",
      icon: Grid3x3, 
      imageSrc: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGltZXMlMjB0YWJsZSUyMG1hdGhzfGVufDB8fDB8fHww",
      dataAiHint: "times table chalkboard", 
    },
    {
      title: "Number Comparison",
      description: "Compare numbers and choose the biggest or smallest.",
      href: "/math/number-comparison",
      icon: Scaling,
      imageSrc: "https://plus.unsplash.com/premium_photo-1717972599101-33a39b433362?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTEzfHxjaGlsZHJlbiUyMG1hdGhlbWF0aWNzfGVufDB8fDB8fHww",
      dataAiHint: "compare numbers", 
    },
    {
      title: "Number Sequencing",
      description: "Find the missing number in a sequence or complete patterns.",
      href: "/math/number-sequencing",
      icon: Footprints, 
      imageSrc: "https://images.unsplash.com/photo-1659720212900-702e1765621d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fE51bWJlciUyMFNlcXVlbmNpbmclMjBGdW58ZW58MHx8MHx8fDA%3D",
      dataAiHint: "number sequence pattern", 
    },
  ];

  return (
    <div className="space-y-8 max-w-4xl lg:max-w-5xl mx-auto">
      <header className="text-center space-y-4 animate-in fade-in-0 slide-in-from-top-10 duration-700 ease-out">
        <div className="relative w-full max-w-md mx-auto h-48 md:h-64 rounded-lg overflow-hidden shadow-lg">
          <Image 
            src="https://images.unsplash.com/photo-1718306201865-cae4a08311fe?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzR8fGNoaWxkcmVuJTIwbWF0aGVtYXRpY3MlMjBiYWNrZ3JvdW5kfGVufDB8fDB8fHww" 
            alt="Abstract math background with numbers and shapes"
            layout="fill"
            objectFit="cover"
            className="rounded-lg"
            data-ai-hint="math background" 
          />
          <div className="absolute inset-0 bg-black/60" /> {/* Dark overlay */}
          <div className="absolute inset-0 flex flex-col items-center justify-center p-4 text-center">
            <Sigma className="h-12 w-12 md:h-16 md:w-16 text-primary drop-shadow-lg animate-in fade-in zoom-in-50 duration-1000 delay-200" aria-hidden="true" />
            <h1 className="text-3xl md:text-4xl font-bold text-gradient-primary-accent mt-2 drop-shadow-md">Math Zone</h1>
            <p className="text-md md:text-lg text-gray-100 drop-shadow-sm mt-1">Explore various math activities and games.</p>
          </div>
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {mathSections.map((section, index) => (
          <Card 
            key={section.title} 
            className="shadow-lg hover:shadow-xl transition-shadow duration-300 ease-in-out animate-in fade-in-0 slide-in-from-bottom-5 duration-500 ease-out overflow-hidden group"
            style={{ animationDelay: `${100 + index * 100}ms` }} // Staggered animation
          >
             <div className="relative h-48 w-full">
               <Image
                src={section.imageSrc}
                alt={section.title}
                layout="fill"
                objectFit="cover"
                className="opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-300 ease-in-out"
                data-ai-hint={section.dataAiHint}
              />
              <div className="absolute inset-0 bg-black/60 group-hover:bg-black/50 transition-colors flex flex-col items-center justify-center text-center p-2">
                 <section.icon className="h-12 w-12 text-white/90 opacity-90 drop-shadow-lg mb-2" />
                 <h3 className="text-xl font-semibold text-white drop-shadow-md">{section.title}</h3>
              </div>
            </div>
            <CardHeader className="flex flex-row items-center gap-4 space-y-0 pb-2 pt-4">
              <section.icon className="h-8 w-8 text-accent hidden" aria-hidden="true" />
              <div className="flex-1">
                <CardTitle className="text-2xl font-semibold text-primary">{section.title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <CardDescription className="text-base text-foreground/80 min-h-[40px]">
                {section.description}
              </CardDescription>
              <Button asChild className="w-full btn-glow">
                <Link href={section.href}>
                  Go to {section.title}
                </Link>
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

