
import type { Puzzle, BookOpenCheck } from 'lucide-react'; // Example, adjust as needed

export interface TutorialStep {
  id: string;
  title: (username?: string | null) => string;
  content: string;
  ariaLabel: string;
  icon?: React.ElementType; // For an icon in the step if desired
  targetElementSelector?: string; // For interactive walkthrough targeting
}

export const tutorialStepsData: TutorialStep[] = [
  {
    id: 'welcome',
    title: (username) => username ? `Welcome, ${username}!` : 'Welcome to ChillLearn AI!',
    content: "This guide will walk you through the main features of the ChillLearn AI application, helping you make the most of your learning experience. Let's get started! You can also launch an interactive walkthrough using the button above.",
    ariaLabel: 'Welcome section introduction',
    targetElementSelector: '#main-header', // Example
  },
  {
    id: 'learn',
    title: () => "Learn Words Page (Your Starting Point - '/learn')",
    content: "The 'Learn' page (found at /learn) is where your literacy journey begins.\n\n1. AI Word Suggestions: Set your desired reading level (e.g., beginner, intermediate) and preferred word length.\n2. Get Ideas: Click 'Get New Word Ideas', and our AI will suggest words tailored to your settings.\n3. Build Your List: See a word you like? Click on it! It'll be added to 'Your Practice Word List' below.\nThis list is crucial as it populates words for your spelling, identification, reading, and AI word game practices.",
    ariaLabel: "Explanation of the Learn Words page (now at /learn) features including AI suggestions and practice list.",
    targetElementSelector: '[data-tour-id="learn-page-card"]', // Example
  },
  {
    id: 'spell',
    title: () => 'Spell Practice Page (Sharpen Your Skills)',
    content: "Navigate to the 'Spell' page to practice spelling words from your list.\n\n1. Current Word: The word you need to spell is displayed prominently.\n2. Your Turn: Type your spelling attempt into the input field.\n3. Check It: Click 'Check Spelling'. If you're correct, the word is marked as 'mastered', and you'll automatically move to the next word in your list. If not, you'll get a hint to try again!",
    ariaLabel: "Guide to the Spell Practice page, how to input spellings and what happens on correct or incorrect attempts.",
    targetElementSelector: '[data-tour-id="spell-page-card"]',
  },
  {
    id: 'identify',
    title: () => 'Identify Word Game (Test Your Recognition)',
    content: "Head to the 'Identify' page for a fun word recognition game.\n\n1. Listen & See: The current word will be displayed and spoken.\n2. Choose Wisely: Select the matching word from a set of multiple-choice options.\n3. Feedback: Get immediate feedback on your choice and automatically proceed to the next word.",
    ariaLabel: "Instructions for the Identify Word game, covering word display, multiple choice options, and feedback.",
    targetElementSelector: '[data-tour-id="identify-page-card"]',
  },
  {
    id: 'read',
    title: () => 'Read Passages Page (Reading in Context)',
    content: "The 'Read' page brings your learned words to life!\n\n1. Generate Story: Click 'Generate New Passage'. The AI will create a short story using words from your practice list and suited to your reading level.\n2. Read or Listen: You can read the passage yourself or click 'Read Aloud' to hear it narrated. Words from your practice list and the currently spoken word will be highlighted.",
    ariaLabel: "Instructions for the Read Passages page, covering passage generation and read aloud features.",
    targetElementSelector: '[data-tour-id="read-page-card"]',
  },
  {
    id: 'ai-games',
    title: () => 'AI Word Games (Interactive Fun)',
    content: "Visit the 'AI Games' section for more engaging ways to practice your vocabulary.\n\n- Fill in the Blank: Read a sentence generated by AI and choose the correct word (from your practice list or similar) to complete it.\n- Word Definition Match: Test your understanding by matching words to their AI-generated definitions.",
    ariaLabel: "Overview of the AI Word Games section, featuring Fill in the Blank and Definition Match.",
    icon: "Puzzle" as any, // Will be resolved to Lucide icon in component
    targetElementSelector: '[data-tour-id="ai-games-page-card"]',
  },
  {
    id: 'math',
    title: () => 'Math Zone (Explore Numeracy)',
    content: "The 'Math Zone' is your hub for various math activities:\n\n- AI Word Problems & Story Problems: Solve math challenges created by AI, tailored to different difficulty levels.\n- Arithmetic Games: Tackle addition, subtraction, multiplication, and division problems.\n- Times Table Practice: Master your multiplication facts for specific tables.\n- Number Comparison: Identify the larger or smaller number in a pair.\n- Number Sequencing: Complete number patterns by finding the missing element.\nMany math games feature optional audio read-aloud for questions and voice input for answers!",
    ariaLabel: "Overview of the Math Zone and its various game sections including AI problems, Arithmetic, Times Table, Comparison and Sequencing.",
    targetElementSelector: '[data-tour-id="math-zone-page-card"]',
  },
  {
    id: 'profile',
    title: () => 'Profile Page (Track Your Progress)',
    content: "Visit your 'Profile' page for a snapshot of your learning journey.\nHere you'll find:\n- Your name and favorite topics (editable!).\n- Number of words in your practice list.\n- Count of words you've successfully mastered.\n- Your currently set reading level and word length preferences for suggestions.",
    ariaLabel: "Overview of the Profile page and the learning statistics and preferences it displays.",
    targetElementSelector: '[data-tour-id="profile-nav-link"]',
  },
  {
    id: 'settings',
    title: () => 'Settings Page (Customize Your App)',
    content: "Tailor the ChillLearn AI app to your liking on the 'Settings' page.\nYou can adjust:\n- Theme: Choose between light, dark, or system default.\n- Font: Select your preferred font family and size.\n- Audio: Enable or disable sound effects, and fine-tune speech settings like voice, rate, and pitch for the read-aloud features.",
    ariaLabel: "Details on the Settings page for customizing appearance and audio preferences.",
    targetElementSelector: '[data-tour-id="settings-nav-link"]',
  },
  {
    id: 'navigation',
    title: () => 'Navigating the App',
    content: "Getting around is easy:\n- Main Homepage ('/'): Your dashboard for quick access to all learning areas.\n- Learn Words ('/learn'): The dedicated page for finding and managing your practice words.\n- Desktop/Tablet: Use the navigation links at the top of the page.\n- Mobile: A handy bottom navigation bar provides quick access to all sections. There's also a Quick Link FAB (Floating Action Button) for fast access to main pages.\n- Quick Learn Button: This button (in the main navigation or mobile sheet menu) takes you directly to the '/learn' page.",
    ariaLabel: "How to navigate the application on different devices using the navigation bars, quick link FAB, and understanding the main homepage vs. learn words page.",
    targetElementSelector: '[data-tour-id="main-navigation"]',
  },
];

export const walkthroughModalSteps: TutorialStep[] = [
 { id: 'intro-modal', title: (username) => username ? `Hi ${username}, Welcome!` : 'Welcome to ChillLearn!', content: "Let's quickly see where everything is. This tour will highlight key sections.", ariaLabel: 'Modal: Introduction', targetElementSelector: 'body' },
  { id: 'home-modal', title: () => "Homepage", content: "This is your main dashboard. From here, you can jump to any learning activity like learning new words, spelling, reading, math, or AI games.", ariaLabel: 'Modal: Homepage', targetElementSelector: '[data-tour-id="main-content-area"]' }, // Assuming your main content area has an ID or data attribute
  { id: 'learn-modal', title: () => "Learn Words Area", content: "Go to 'Learn Words' (usually from the top or bottom nav) to find new words with AI, set your learning level, and manage your personal practice list. This list is key for other activities!", ariaLabel: 'Modal: Learn Words Area', targetElementSelector: '[href="/learn"]' },
  { id: 'activities-modal', title: () => "Activity Hubs", content: "Sections like 'Spell', 'Identify', 'Read', 'AI Games', and 'Math Zone' are where you'll practice and play. They use words from your 'Learn Words' list.", ariaLabel: 'Modal: Activity Hubs', targetElementSelector: '[href="/spell"]' }, // Target one of them
  { id: 'profile-settings-modal', title: () => "Profile & Settings", content: "Check your 'Profile' to see progress and update your name/topics. In 'Settings', you can change the app's look and sound.", ariaLabel: 'Modal: Profile and Settings', targetElementSelector: '[href="/profile"]'},
  { id: 'finish-modal', title: () => "You're Ready!", content: "That's the basics! Explore and have fun learning. You can find this full guide on the 'Guide' page if you need a refresher.", ariaLabel: 'Modal: End of tour', targetElementSelector: 'body' }
];
